version: "3.7"

services:
  build:
    image: node:14.15.0
    working_dir: /app
    volumes:
      - ./:/app
    command: npm run watch
  serve:
    image: node:14.15.0
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3333:3333
    command: npm run start
